### ISSUE TITLE
pip needs to be updated

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#151]
https://github.com/pypa/pip/commit/90b1179b7641784e4658732a89a4a2f93f4939e9

**Comment by robby-dermody** [comment]
why does it need to be updated? will this --isolated flag fix some things under 14.04 (the mess that is 12.04 aside)?

**Comment by rippler** [comment]
I was thinking about that, but "needs" is too strong a word.
Maybe it'd help us, but the other day I tried to use the latest version and it messed up my system. If it'd require effort for no measurable benefit, please close/ignore this.
