### ISSUE TITLE
Missing counterparty-cli dependencies

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#171]
`counterparty-cli` doesn't work (see https://github.com/CounterpartyXCP/counterpartyd/issues/573).
It seems while stuff was moved to `counterparty-cli`, the deps didn't. I had to install the following:
```
python-dateutils
prettytable
requests
pysha3
bitcoin
```
I got this far but then `ripemd` was missing and `pycrypto` is already installed, so...

```
C:\Windows\system32>python -V
Python 3.4.2
C:\Windows\system32>counterpartyd -V
C:\Windows\system32>echo off
counterpartyd v9.49.3
```
I should mention that I suspect that this may be due to the fact that I'm testing Python 3.4.2. I just installed the binary Pycrypto package (which I had installed for Python 3.4.1) and installed the same version of `pycrypto` (2.6.1) as before and the problem still occurs, so I'm curious if other are seeing the same on Windows with Python 3.4.1.

**Comment by rippler** [comment]
Also on Linux (Ubuntu 14.04):
```
rippler@ubuntu:/home/xcp$ counterpartyd -V
counterpartyd v9.49.3
rippler@ubuntu:/home/xcp$ python3 -V
Python 3.4.0
rippler@ubuntu:/home/xcp$ /home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py --help
Traceback (most recent call last):
  File "/home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py", line 9, in <module>
    import dateutil.parser
ImportError: No module named 'dateutil'
```

**Comment by adamkrellenstein** [comment]
`bitcoin` is the wrong library. You want `python-bitcoinlib` (which is imported with `import bitcoin`).

**Comment by rippler** [comment]
After additional fiddling:
* python-bitcoinlib
* colorlog
* flask
* flask-httpauth
* pycoin
* tornado
* jsonrpc
* dispatcher

Once I get to this point, I get stuck again.

Win:
* `pip3 install dispatcher` fails (there's an error in the package)
* Building from source doesn't help solve the missing module error (same error as on Linux, below)

Ubuntu:
```
Traceback (most recent call last):
  File "/home/xcp/counterpartyd_build/dist/counterpartyd/counterparty-cli.py", line 17, in <module>
    from lib import config, util, exceptions, backend, database, transaction, script, api
  File "/home/xcp/counterpartyd_build/dist/counterpartyd/lib/api.py", line 26, in <module>
    from jsonrpc import dispatcher
```
Installing (`sudo pip3 install dispatcher`) the package doesn't fix this error - this is after `dispatcher` has been installed. 

Maybe I'll look into this tomorrow.

**Comment by rippler** [comment]
One more was missing : 
* json-rpc

And I'll summarize the list of all modules that I had to install:
* python-bitcoinlib
* colorlog
* flask
* flask-httpauth
* pycoin
* tornado
* dispatcher
* dateutils
* prettytable
* requests
* pysha3
* pycrypto

```
sudo pip3 install json-rpc colorlog python-bitcoinlib pycoin flask \
  flask-httpauth tornado dispatcher dateutils prettytable requests \
  pysha3 pycrypto
```
Now I can run `counterparty-cli.py --help` without any errors. I still get errors with actual commands, but that's another issue.

@robby-dermody can you verify and add these to setup script(s)?

**Comment by mtbitcoin** [comment]
@rippler  I am still getting the "ImportError: No module named 'dateutil' even after installing all of the dependencies

**Comment by rippler** [comment]
@mtbitcoin, happy New Year and thanks for the testnet thing! 
Do you have `dateutils` (I'm not sure if `dateutil` is a typo?) installed?

```
C:\Windows\system32>python c:\counterpartyd_build\dist\counterpartyd\counterpart
y-cli.py --testnet --data-dir c:\bitcoin-core-0.10\counterparty-testnet --config
-file c:\bitcoin-core-0.10\TESTNET.counterpartyd.conf market
Your Pending Order Matches
+------------------+-----------+
| Matched Order ID | Time Left |
+------------------+-----------+
+------------------+-----------+
...
````

As you can see I'm running this with Bitcoin Core 0.10.0 (and these [binaries](https://github.com/rippler/bitcoin-core-0.10.0-addrindex)) because I want to suffer more :-)

Here's what I got installed with `pip3`.  (I haven't removed `bitcoin` and some other modules that probably aren't necessary, because it appears to be working fine...)
```
appdirs (1.2.0)
apsw (3.8.5.post1)
argparse (1.3.0)
bip32utils (0.1)
bitcoin (1.1.23)
bitcoin-python (0.3)
certifi (14.5.14)
colorlog (2.4.0)
dateutils (0.6.6)
dispatcher (1.0)
ecdsa (0.11)
Flask (0.10.1)
Flask-HTTPAuth (2.3.0)
itsdangerous (0.24)
Jinja2 (2.7.3)
json-rpc (1.8.1)
jsonrpc (1.2)
MarkupSafe (0.23)
pip (1.4.1)
prettytable (0.7.2)
progressbar33 (2.4)
pycoin (0.52)
pycrypto (2.6.1)
pysha3 (0.3)
python-bitcoinlib (0.2.1)
python-dateutil (2.3)
pytz (2014.10)
pywin32 (219)
requests (2.5.1)
setuptools (9.1)
six (1.8.0)
tornado (4.0.2)
virtualenv (1.11.6)
Werkzeug (0.9.6)
```

**Comment by robby-dermody** [comment]
The problem is that counterparty-cli is for some reason using the main system path, instead of the virtual environment at ~xcp/counterpartyd_build/env

**Comment by rippler** [comment]
@robby-dermody can we close this or do you need to make additional changes to the code?
