### ISSUE TITLE
Handling of MissingSectionHeaderError

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#177]
Missed the opening square bracket (`[`) in `counterpartyd.conf`:
```
rippler@ubuntu:~$ ps -ef | grep counter
root      7903     1  0 09:24 ?        00:00:00 runsvdir -P /etc/service log: ile 
"/usr/lib/python3.4/configparser.py", line 1058, in _read     raise MissingSectionHeaderError(fpname, \ 
lineno, line) configparser.MissingSectionHeaderError: File contains no section headers. file: \
'/home/rippler/.config/counterpartyd-testnet/counterpartyd.conf', line: 1 'Default]\n' [INFO] Running \
v9.49.3 of counterpartyd.?[0m [INFO] Connecting to backend.?[0m [INFO] Checking version.?[0m \
```

I don't know if we should do anything about this, but restarting automaticlaly doesn't help - the sooner this fails the better. 
Maybe we could handle this the same way as missing `counterpartyd.conf` file?

**Comment by robby-dermody** [comment]
This is a counterpartyd issue, I think

**Comment by adamkrellenstein** [comment]
The build system put a typo in the config file? That's not a counterpartyd problem.

**Comment by rippler** [comment]
@adamkrellenstein the typo was made by me (high latency + vi editor), perhaps I should have emphasized that.
