### ISSUE TITLE
Lines should be wrapped for better usability of docs

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd_build#24]
From the "Wrap Your Lines" department:
![codebleed](https://cloud.githubusercontent.com/assets/4045519/2930453/85b45900-d796-11e3-822d-596fac7021b7.jpg)

It's really a Github issue rather than any kind of bug, but this is to let everyone know that we may need to start line-wrapping online docs otherwise their PDF versions (presumably, great for offline use) will remain much less useful and HTML pages will continue to require horizontal scrolling.

Source:
https://media.readthedocs.org/pdf/counterpartyd-build/latest/counterpartyd-build.pdf

**Comment by robby-dermody** [comment]
please submit specific pull requests where/if this is still a problem, to fix. thanks

**Comment by rippler** [comment]
That's from readthedocs (May 2014), we can ignore it.
